---
title: "p8105_finalproject_shiny"
author: "Carolina Downie"
date: "11/30/2017"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(janitor)
library(stringr)
library(ggridges)
library(ggthemes)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
library(httr)
library(jsonlite)

hospital_data <- read_csv(file = "./data/Hospital_General_Information.csv", col_names = TRUE) %>% 
  clean_names() %>% 
  select(-address) %>%
  mutate(hospital_overall_rating = as.numeric(hospital_overall_rating)) %>%
  filter(!is.na(hospital_overall_rating)) %>%
  separate(location, into = c("address", "coordinates"), sep = "\\(") %>% 
  mutate(coordinates = str_sub(coordinates, 1, -2)) %>%
  filter(!is.na(coordinates)) %>%
separate(coordinates, into = c("latitude", "longitude"), sep = ",") %>%
  mutate(latitude = as.numeric(latitude), longitude = as.numeric(longitude))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
star_choice <- hospital_data %>% 
  distinct(hospital_overall_rating) %>% arrange(desc(hospital_overall_rating))
# selectInput widget
shiny::selectInput("star_choice", label = h3("Select Star"),
            choices = star_choice, selected = "5")
```




Row
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({ 
  
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showland = TRUE,
  landcolor = toRGB("gray95"),
  subunitcolor = toRGB("gray85"),
  countrycolor = toRGB("gray85"),
  countrywidth = 0.5,
  subunitwidth = 0.5
)

filter(hospital_data, hospital_overall_rating == input$star_choice) %>%
  plot_geo(lat = ~latitude, lon = ~longitude) %>%
  add_markers(
    text = ~paste(hospital_name, city, state, sep = "<br />"),
    symbol = I("circle"), size = I(8), hoverinfo = "text"
    ) %>%
  layout(title = 'Hospital Rankings/>(Hover for Hospital)', geo = g)
 
})
  
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

